on: [pull_request]

jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      - name: Get author
        uses: actions/github-script@v5
        with:
          script: |
            let response = await github.rest.git.createTag({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag: "potato",
              message: "yes",
              object: "9f9240f0a442e3a391115551b40676ba6bd2d11e",
              type: "commit"
            });
            console.log(response);
